[".local/bin/takeout-merge"]
    type = "file"
    url = "https://raw.githubusercontent.com/its-me/google-takeout/main/takeout-merge"
    executable = true

[".local/bin/takeout"]
    type = "file"
    url = "https://raw.githubusercontent.com/its-me/google-takeout/main/takeout"
    executable = true
