[tasks]
image_bound = [0, 0]

[open]
rules = [
  { mime = "application/pdf", use = "chrome" },
  { mime = "message/rfc822", use = "chrome" },
  { name = "*.mhtml", use = "chrome" },
  { name = "*.mht", use = "chrome" },
  { mime = "image/*", use = "vui" },
]

[opener]
chrome = [
  { run = 'google-chrome-stable "$@"', orphan = true, desc = "Open in Chrome" }
]
vui = [
  { run = 'viu "$1"', desc = "viu", block = true }
]
